function TableS2

load('Data.mat');

biasTable = array2table([Data.Subjects.Behavior.FaceVase.Bias.df'  ...
                        Data.Subjects.Behavior.FaceVase.Bias.z' ...
                        Data.Subjects.Behavior.FaceVase.Bias.p' ...
                        Data.Subjects.Behavior.Cube.Bias.df' ...
                        Data.Subjects.Behavior.Cube.Bias.z' ...
                        Data.Subjects.Behavior.Cube.Bias.p'],'variableNames', ...
                        {'FaceVase_df', 'FaceVase_z','FaceVase_p',...
                         'Cube_df', 'Cube_z','Cube_p'});
disp(biasTable);
               